"use client";
import {useEffect,useState} from "react";
import type {Lang,Room} from "../../data";

const copy={
  en:{rooms:"Rooms",services:"Services",contact:"Contact",submit:"Submit inquiry",back:"Back to all stays",more:"View more photos",guests:"Guests",bedrooms:"Bedrooms",beds:"Beds",bathrooms:"Bathrooms",about:"About this place",amenities:"Amenities",highlights:"Property Highlights",nearby:"Explore Nearby",stay:"Your Malaysia stay",interested:"Interested in this room?",reply:"Tell us your dates and group size. We’ll help confirm availability.",inquire:"Inquire about this room",benefits:["Chinese-speaking support","Transfers can be arranged","Local services available"]},
  zh:{rooms:"房源",services:"当地服务",contact:"联系我们",submit:"提交咨询",back:"返回所有房源",more:"查看更多照片",guests:"位客人",bedrooms:"间卧室",beds:"张床",bathrooms:"间浴室",about:"房源介绍",amenities:"房间设施",highlights:"房源亮点",nearby:"周边探索",stay:"马来西亚精选住宿",interested:"想了解入住详情？",reply:"告诉我们入住日期和人数，我们会帮您确认房源情况。",inquire:"咨询入住",benefits:["中文沟通","可安排接送","可提供当地服务"]}
};

export function RoomDetail({room}:{room:Room}){
 const [lang,setLang]=useState<Lang>("zh"),[open,setOpen]=useState(false),[active,setActive]=useState(0);const t=copy[lang];
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!open)return;if(e.key==="Escape")setOpen(false);if(e.key==="ArrowRight")setActive(v=>(v+1)%room.images.length);if(e.key==="ArrowLeft")setActive(v=>(v-1+room.images.length)%room.images.length)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[open,room.images.length]);
 const show=(i:number)=>{setActive(i);setOpen(true)};
 return <><header><a className="logo" href="/"><span className="logo-mark">⌂</span><span><b>MY MALAYSIA</b><small>STAY &amp; TRAVEL</small></span></a><nav><a href="/#stays">{t.rooms}</a><a href="/#services">{t.services}</a><a href="/#contact">{t.contact}</a></nav><div className="header-right"><div className="language-switch"><button className={lang==="zh"?"active":""} onClick={()=>setLang("zh")}>中文</button><i/> <button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>English</button></div><a className="button header-cta" href="/#contact">{t.submit}</a></div></header>
 <main className="room-detail"><a className="back-link" href="/#stays">← {t.back}</a><section className="detail-gallery"><button onClick={()=>show(0)}><img src={room.images[0]} alt={room.name[lang]}/></button>{room.images.slice(1,5).map((img,i)=><button onClick={()=>show(i+1)} key={img}><img src={img} alt={`${room.name[lang]} ${i+2}`}/>{i===3&&<span className="photo-count">+{room.images.length-5}<small>{t.more}</small></span>}</button>)}</section>
 <section className="detail-layout"><div className="detail-main"><p className="detail-location">{room.location[lang]}, Malaysia</p><h1>{room.name[lang]}</h1><div className="detail-stats"><span><b>{room.guests}</b> {t.guests}</span><span><b>{room.bedrooms}</b> {t.bedrooms}</span><span><b>{room.beds}</b> {t.beds}</span><span><b>{room.bathrooms}</b> {t.bathrooms}</span><span className="area-stat"><b>⌖</b> {room.area[lang]}</span></div><div className="detail-section"><h2>{t.about}</h2><p>{room.description[lang]}</p></div><div className="detail-section"><h2>{t.amenities}</h2><div className="amenity-grid">{room.amenities.map(a=><div key={a.name.en}><span>{a.icon}</span>{a.name[lang]}</div>)}</div></div><div className="detail-section"><h2>{t.highlights}</h2><div className="highlight-grid">{room.highlights.map(h=><div key={h.name.en}><span>{h.icon}</span><b>{h.name[lang]}</b></div>)}</div></div><div className="detail-section"><h2>{t.nearby}</h2><div className="nearby-list">{room.nearbyPlaces.map(p=><div key={p.name.en}><span>{p.icon}</span><p><b>{p.name[lang]}</b><em>{p.category[lang]}</em><small>{p.distance[lang]}</small></p><i>→</i></div>)}</div></div></div><aside className="detail-aside"><p className="eyebrow">{t.stay}</p><h2>{t.interested}</h2><p>{t.reply}</p><ul className="inquiry-benefits">{t.benefits.map(item=><li key={item}>✓ {item}</li>)}</ul><a className="button" href="/#contact">{t.inquire}</a></aside></section>
 </main><footer><a className="logo" href="/"><span className="logo-mark">⌂</span><span><b>MY MALAYSIA</b><small>STAY &amp; TRAVEL</small></span></a><p>{lang==="zh"?"马来西亚舒适住宿与私人当地旅行服务。":"Comfortable stays and private local travel services across Malaysia."}</p><div><a href="/#stays">{t.rooms}</a><a href="/#services">{t.services}</a><a href="/#contact">{t.contact}</a></div><small>© 2026 MY Malaysia Stay &amp; Travel</small></footer>
 {open&&<div className="gallery-modal" role="dialog" aria-modal="true" aria-label="Photo gallery"><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close gallery">×</button><button className="modal-prev" onClick={()=>setActive((active-1+room.images.length)%room.images.length)} aria-label="Previous photo">‹</button><figure><img src={room.images[active]} alt={`${room.name[lang]} ${active+1}`}/><figcaption>{active+1} / {room.images.length}</figcaption></figure><button className="modal-next" onClick={()=>setActive((active+1)%room.images.length)} aria-label="Next photo">›</button><div className="modal-thumbs">{room.images.map((img,i)=><button className={i===active?"active":""} onClick={()=>setActive(i)} key={img}><img src={img} alt=""/></button>)}</div></div>}</>;
}
