"use client";
import Link from "next/link";
import {useState} from "react";
import type {ServiceItem} from "../../../../db/service-items";
const sections=["基本信息","接送与车型","图片","咨询规则"],required=["接送日期","接机 / 送机","航班号","酒店 / 接送地址","同行人数","行李数量"],optional=["儿童人数","儿童座椅","特殊需求"];
const emptyVehicle={image:"",nameZh:"新车型",nameEn:"",people:"",luggage:"",description:"",price:0,visible:true,internalNote:""};
export function TransferEditor({data,onChange}:{data:ServiceItem;onChange:(x:ServiceItem)=>void}){
 const[d,setD]=useState({...data,vehicles:data.vehicles.length?data.vehicles:[{...emptyVehicle,nameZh:"舒适轿车",nameEn:"Sedan",people:"1–3 人",luggage:"2–3 件",description:"少人数出行"}],airports:data.airports.length?data.airports:["KLIA","KLIA2"],directions:data.directions.length?data.directions:["机场 → 酒店 / 市区","酒店 / 市区 → 机场"]}),[tab,setTab]=useState(0),[editing,setEditing]=useState<number|null>(null),[notice,setNotice]=useState("");
 const set=(k:keyof ServiceItem,v:any)=>setD(x=>({...x,[k]:v}));
 const save=async()=>{const next={...d,inquiryFields:[...required,...optional],inquiryRequired:required,inquiryPromptFields:required};setNotice("保存中…");const r=await fetch(`/api/admin/service-items/${d.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(r.ok){setD(next);onChange(next);setNotice("✓ 已保存并更新前端")}else setNotice("保存失败，请重试")};
 const upload=async(files:FileList|null,target:"service"|number)=>{if(!files?.length)return;const f=new FormData();[...files].forEach(x=>f.append("files",x));const r=await fetch("/api/admin/uploads",{method:"POST",body:f}),x=await r.json();if(!r.ok)return;target==="service"?set("images",[...d.images,...x.urls]):set("vehicles",d.vehicles.map((v,i)=>i===target?{...v,image:x.urls[0]}:v))};
 const list=(a:string[],k:keyof ServiceItem)=><input value={a.join("、")} onChange={e=>set(k,e.target.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean))}/>;
 const uv=(i:number,k:string,v:any)=>set("vehicles",d.vehicles.map((x,n)=>n===i?{...x,[k]:v}:x));
 return <><div className="editor-top"><div><Link href="/admin/services">← 返回服务列表</Link><h1>{d.nameZh}</h1><span>接送机 · {d.city} · <b className="online-dot">●</b> {d.status==="published"?"已上线":"草稿"}</span></div><div><a className="admin-secondary" href={`/services/item/${d.slug}`} target="_blank">预览前台</a><button className="admin-primary" onClick={save}>保存</button></div></div>{notice&&<p className="lead-notice">{notice}</p>}<div className="transfer-editor compact"><aside><small>服务内容</small>{sections.slice(0,3).map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}<hr/><button className={tab===3?"active":""} onClick={()=>setTab(3)}>咨询规则</button></aside><main className="editor-form">
 {tab===0&&<><Head title="基本信息" text="前端弹窗顶部展示的核心信息。"/><div className="compact-form-card"><Field n="城市"><select value={d.city} onChange={e=>set("city",e.target.value)}>{["吉隆坡","亚庇","仙本那","马六甲"].map(x=><option key={x}>{x}</option>)}</select></Field><div className="field-row"><Field n="中文名称"><input value={d.nameZh} onChange={e=>set("nameZh",e.target.value)}/></Field><Field n="英文名称"><input value={d.nameEn} onChange={e=>set("nameEn",e.target.value)}/></Field></div><Field n="副标题"><input value={d.subtitleZh} onChange={e=>set("subtitleZh",e.target.value)}/></Field><Field n="服务标签">{list(d.tags,"tags")}</Field><div className="field-row"><Field n="最大接待"><div className="input-suffix"><input type="number" value={d.maxGuests} onChange={e=>set("maxGuests",Number(e.target.value))}/><span>人</span></div></Field><Field n="前端人数文案"><input value={d.guestNote} onChange={e=>set("guestNote",e.target.value)}/></Field></div></div></>}
 {tab===1&&<><Head title="接送与车型" text="客户先看接送范围，再看可以安排哪些车辆。"/><section className="compact-form-card"><h3>接送范围</h3><div className="field-row"><Field n="机场">{list(d.airports,"airports")}</Field><Field n="主要服务区域">{list(d.serviceAreas,"serviceAreas")}</Field></div><Field n="服务方向">{list(d.directions,"directions")}</Field><Field n="其他区域"><input value={d.otherAreaNote} onChange={e=>set("otherAreaNote",e.target.value)}/></Field></section><div className="vehicle-list-head"><div><h3>可安排车型</h3><p>先查看车辆，只有点击编辑时才展开字段。</p></div><button onClick={()=>{set("vehicles",[...d.vehicles,{...emptyVehicle}]);setEditing(d.vehicles.length)}}>＋ 添加车型</button></div><div className="vehicle-summary-list">{d.vehicles.map((v,i)=><article key={i} className={editing===i?"editing":""}><div className="vehicle-thumb">{v.image?<img src={v.image} alt=""/>:<span>🚗</span>}</div><div className="vehicle-summary"><h3>{v.nameZh}</h3><small>{v.nameEn||"英文名称待填写"}</small><p>👤 {v.people||"人数待填写"}　🧳 {v.luggage||"行李待填写"}</p><span>{v.description||"适用说明待填写"}</span></div><div className="vehicle-summary-actions"><i className={v.visible?"visible":""}>● {v.visible?"前台显示":"已隐藏"}</i><button onClick={()=>setEditing(editing===i?null:i)}>{editing===i?"收起":"编辑"}</button></div>{editing===i&&<div className="vehicle-drawer"><label className="vehicle-image-upload">{v.image?<img src={v.image} alt=""/>:<span>上传车辆图片</span>}<input type="file" accept="image/*" onChange={e=>upload(e.target.files,i)}/></label><div><div className="field-row"><Field n="中文名称"><input value={v.nameZh} onChange={e=>uv(i,"nameZh",e.target.value)}/></Field><Field n="英文名称"><input value={v.nameEn} onChange={e=>uv(i,"nameEn",e.target.value)}/></Field></div><div className="field-row"><Field n="建议人数"><input value={v.people} onChange={e=>uv(i,"people",e.target.value)}/></Field><Field n="建议行李"><input value={v.luggage} onChange={e=>uv(i,"luggage",e.target.value)}/></Field></div><Field n="适用说明"><input value={v.description} onChange={e=>uv(i,"description",e.target.value)}/></Field><Field n="内部备注"><input value={v.internalNote} onChange={e=>uv(i,"internalNote",e.target.value)}/></Field><div className="vehicle-actions"><label><input type="checkbox" checked={v.visible} onChange={e=>uv(i,"visible",e.target.checked)}/> 前台显示</label><button onClick={()=>{set("vehicles",d.vehicles.filter((_,n)=>n!==i));setEditing(null)}}>删除车型</button></div></div></div>}</article>)}</div></>}
 {tab===2&&<><Head title="服务图片" text="用于服务列表和接送详情弹窗，第一张图片是当前封面。"/><div className="compact-gallery">{d.images.map((x,i)=><article key={x}><img src={x} alt=""/><b>{i===0?"★ 当前封面":`图片 ${i+1}`}</b><button onClick={()=>set("images",d.images.filter(y=>y!==x))}>删除</button></article>)}<label>＋ 上传图片<input type="file" multiple accept="image/*" onChange={e=>upload(e.target.files,"service")}/></label></div>{!d.images.length&&<p className="empty-gallery">还没有服务图片，上传后这里会直接变成图库。</p>}</>}
 {tab===3&&<><Head title="咨询规则" text="所有接送机服务共用同一套咨询模板，无需按城市重复配置。"/><section className="consult-template"><h3>接送服务默认需要客户提供</h3>{required.map(x=><span key={x}>✓ {x}</span>)}<h3>可选信息</h3>{optional.map(x=><span className="optional" key={x}>○ {x}</span>)}<Link href="/admin/services/templates">编辑接送机咨询模板 →</Link></section><section className="default-flow"><b>统一服务流程</b><span>01 告诉我们行程</span><span>02 匹配车型</span><span>03 安心出发</span></section></>}
 </main></div></>}
function Head({title,text}:{title:string;text:string}){return <div className="block-head"><h2>{title}</h2><p>{text}</p></div>};function Field({n,children}:{n:string;children:React.ReactNode}){return <label className="field"><span>{n}</span>{children}</label>}
