"use client";
import Link from "next/link";
import {useState} from "react";
import type {ServiceItem} from "../../../../db/service-items";
const sections=["基础信息","车型与接送范围","图片","咨询设置"];
const fields=["接送日期","航班号","接机 / 送机","酒店 / 接送地址","同行人数","行李数量","儿童人数","儿童座椅","特殊需求","联系方式"];
const vehicle={image:"",nameZh:"舒适轿车",nameEn:"Sedan",people:"1–3 人",luggage:"2–3 件",description:"少人数出行",price:0,visible:true,internalNote:""};
export function TransferEditor({data,onChange}:{data:ServiceItem;onChange:(x:ServiceItem)=>void}){
 const[d,setD]=useState({...data,vehicles:data.vehicles.length?data.vehicles:[vehicle],airports:data.airports.length?data.airports:["KLIA","KLIA2"],directions:data.directions.length?data.directions:["机场 → 酒店 / 市区","酒店 / 市区 → 机场"],inquiryFields:data.inquiryFields.length?data.inquiryFields:fields.slice(0,6),inquiryRequired:data.inquiryRequired.length?data.inquiryRequired:fields.slice(0,6),inquiryPromptFields:data.inquiryPromptFields.length?data.inquiryPromptFields:fields.slice(0,6)}),[tab,setTab]=useState(0),[notice,setNotice]=useState(""),[preview,setPreview]=useState("弹窗");
 const set=(k:keyof ServiceItem,v:any)=>setD(x=>({...x,[k]:v}));
 const save=async(status?:ServiceItem["status"])=>{const next={...d,status:status||d.status};setNotice("保存中…");const r=await fetch(`/api/admin/service-items/${d.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(r.ok){setD(next);onChange(next);setNotice(status==="published"?"✓ 服务已更新":"✓ 草稿已保存")}else setNotice("保存失败，请重试")};
 const upload=async(files:FileList|null,target:"service"|number)=>{if(!files?.length)return;const f=new FormData();[...files].forEach(x=>f.append("files",x));const r=await fetch("/api/admin/uploads",{method:"POST",body:f}),x=await r.json();if(!r.ok)return;target==="service"?set("images",[...d.images,...x.urls]):set("vehicles",d.vehicles.map((v,i)=>i===target?{...v,image:x.urls[0]}:v))};
 const list=(a:string[],k:keyof ServiceItem)=><input value={a.join("、")} onChange={e=>set(k,e.target.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean))}/>;
 const updateVehicle=(i:number,k:string,v:any)=>set("vehicles",d.vehicles.map((x,n)=>n===i?{...x,[k]:v}:x));
 return <><div className="editor-top"><div><Link href="/admin/services">← 返回服务列表</Link><h1>{d.nameZh}</h1><span>接送机 · {d.city} · {d.status==="published"?"已上线":"草稿"}</span></div><div><a className="admin-secondary" href={`/services/item/${d.slug}`} target="_blank">预览前台</a><button className="admin-secondary" onClick={()=>save()}>保存草稿</button><button className="admin-primary" onClick={()=>save("published")}>{d.status==="published"?"更新服务":"发布服务"}</button></div></div>{notice&&<p className="lead-notice">{notice}</p>}<div className="transfer-editor"><aside>{sections.map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}><i>{i+1}</i>{x}</button>)}</aside><main className="editor-form">
 {tab===0&&<><Head title="基础信息" text="直接对应前端弹窗顶部，不再显示重复分类字段。"/><div className="field-row"><Field n="服务类型"><input value="接送机" disabled/></Field><Field n="城市"><select value={d.city} onChange={e=>set("city",e.target.value)}>{["吉隆坡","亚庇","仙本那","马六甲"].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="field-row"><Field n="中文名称"><input value={d.nameZh} onChange={e=>set("nameZh",e.target.value)}/></Field><Field n="英文名称"><input value={d.nameEn} onChange={e=>set("nameEn",e.target.value)}/></Field></div><div className="field-row"><Field n="中文副标题"><input value={d.subtitleZh} onChange={e=>set("subtitleZh",e.target.value)}/></Field><Field n="英文副标题"><input value={d.subtitleEn} onChange={e=>set("subtitleEn",e.target.value)}/></Field></div><Field n="服务标签">{list(d.tags,"tags")}</Field><div className="field-row"><Field n="最大可安排人数"><input type="number" value={d.maxGuests} onChange={e=>set("maxGuests",Number(e.target.value))}/></Field><Field n="人数说明"><input value={d.guestNote} onChange={e=>set("guestNote",e.target.value)}/></Field></div><div className="field-row"><Field n="价格显示"><select value={d.priceMode} onChange={e=>set("priceMode",e.target.value)}><option>起价</option><option>价格咨询</option></select></Field>{d.priceMode==="起价"&&<Field n="价格 RM"><input type="number" value={d.price} onChange={e=>set("price",Number(e.target.value))}/></Field>}</div></>}
 {tab===1&&<><Head title="接送范围" text="机场、方向和区域使用结构化字段。"/><div className="field-row"><Field n="机场">{list(d.airports,"airports")}</Field><Field n="主要服务区域">{list(d.serviceAreas,"serviceAreas")}</Field></div><Field n="服务方向">{list(d.directions,"directions")}</Field><Field n="其他区域"><input value={d.otherAreaNote} onChange={e=>set("otherAreaNote",e.target.value)}/></Field><Head title="可安排车型" text="车型按当前城市服务独立保存。"/><Field n="车型展示方式"><select value={d.vehicleDisplayMode} onChange={e=>set("vehicleDisplayMode",e.target.value)}><option>车型类别</option><option>具体车型</option></select></Field><div className="vehicle-edit-list">{d.vehicles.map((v,i)=><div className="vehicle-edit-card" key={i}><label className="vehicle-image-upload">{v.image?<img src={v.image} alt=""/>:<span>上传车辆图片</span>}<input type="file" accept="image/*" onChange={e=>upload(e.target.files,i)}/></label><div className="field-row"><Field n="前台名称"><input value={v.nameZh} onChange={e=>updateVehicle(i,"nameZh",e.target.value)}/></Field><Field n="英文名称"><input value={v.nameEn} onChange={e=>updateVehicle(i,"nameEn",e.target.value)}/></Field></div><div className="field-row"><Field n="建议人数"><input value={v.people} onChange={e=>updateVehicle(i,"people",e.target.value)}/></Field><Field n="建议行李"><input value={v.luggage} onChange={e=>updateVehicle(i,"luggage",e.target.value)}/></Field></div><Field n="适用说明"><input value={v.description} onChange={e=>updateVehicle(i,"description",e.target.value)}/></Field><Field n="内部备注"><input value={v.internalNote} onChange={e=>updateVehicle(i,"internalNote",e.target.value)}/></Field><div className="vehicle-actions"><label><input type="checkbox" checked={v.visible} onChange={e=>updateVehicle(i,"visible",e.target.checked)}/> 前台显示</label><button onClick={()=>set("vehicles",d.vehicles.filter((_,n)=>n!==i))}>删除</button></div></div>)}</div><button className="add-line" onClick={()=>set("vehicles",[...d.vehicles,{...vehicle,nameZh:"新车型",nameEn:""}])}>＋ 添加车型</button></>}
 {tab===2&&<><Head title="服务封面与图库" text="服务图片与车型图片分开管理，第一张作为封面。"/><label className="service-upload">上传服务图片<input type="file" multiple accept="image/*" onChange={e=>upload(e.target.files,"service")}/></label><div className="service-image-list">{d.images.map((x,i)=><div key={x}><img src={x} alt=""/><b>{i===0?"★ 服务封面":`图库 ${i}`}</b><button onClick={()=>set("images",d.images.filter(y=>y!==x))}>删除</button></div>)}</div></>}
 {tab===3&&<><Head title="咨询设置" text="弹窗提示、表单显示和必填规则分别控制。"/><div className="inquiry-field-table"><div><b>字段</b><b>弹窗提示</b><b>表单显示</b><b>必填</b></div>{fields.map(x=><div key={x}><span>{x}</span>{(["inquiryPromptFields","inquiryFields","inquiryRequired"] as const).map(k=><input key={k} type="checkbox" disabled={k==="inquiryRequired"&&!d.inquiryFields.includes(x)} checked={d[k].includes(x)} onChange={e=>set(k,e.target.checked?[...d[k],x]:d[k].filter(y=>y!==x))}/>)}</div>)}</div><Head title="服务流程" text="接送机使用统一默认流程，无需每个城市重复填写。"/><div className="default-flow"><b>✓ 使用接送机默认流程</b><span>01 告诉我们行程</span><span>02 匹配车型</span><span>03 安心出发</span></div></>}
 </main><aside className="transfer-preview"><div className="preview-switch"><button className={preview==="卡片"?"active":""} onClick={()=>setPreview("卡片")}>列表卡片</button><button className={preview==="弹窗"?"active":""} onClick={()=>setPreview("弹窗")}>详情弹窗</button></div><div className={preview==="卡片"?"preview-card":"preview-modal"}>{d.images[0]&&<img src={d.images[0]} alt=""/>}<small>{d.city} · 接送机</small><h2>{d.nameZh}</h2><p>{d.subtitleZh}</p><div>{d.tags.map(x=><i key={x}>{x}</i>)}</div>{preview==="弹窗"&&<><strong>1–{d.maxGuests} 人均可安排</strong><span>{d.guestNote}</span><h4>可安排车型</h4><div className="preview-vehicles">{d.vehicles.filter(x=>x.visible).slice(0,4).map((x,i)=><div key={i}>{x.image&&<img src={x.image} alt=""/>}<b>{x.nameZh}</b><small>{x.people}</small></div>)}</div><button>咨询这项服务</button></>}</div></aside></div></>}
function Head({title,text}:{title:string;text:string}){return <div className="block-head"><h2>{title}</h2><p>{text}</p></div>};function Field({n,children}:{n:string;children:React.ReactNode}){return <label className="field"><span>{n}</span>{children}</label>}
