"use client";
import Link from "next/link";import {useMemo,useRef,useState} from "react";import type {PropertyRecord} from "../../../db/properties";
const steps=["基础信息","图片","空间信息","介绍","设施","亮点","周边","参考价格","发布"];
const blank:Omit<PropertyRecord,"id"|"updatedAt">={slug:"",nameZh:"",nameEn:"",city:"吉隆坡",areaZh:"",areaEn:"",tags:[],images:[],imageCategories:{},guests:2,bedrooms:1,beds:1,bathrooms:1,descriptionZh:"",descriptionEn:"",amenities:[],highlights:[],nearby:[],priceFrom:0,priceNote:"旺季价格请咨询",status:"draft"};
const amenityOptions=["高速 WiFi","空调","设备齐全的厨房","洗衣机","免费停车","电视","吹风机","亲子友好"];
export function PropertyEditor({initial}:{initial?:PropertyRecord}){
 const [data,setData]=useState(initial||blank);const [step,setStep]=useState(0);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [imageMessage,setImageMessage]=useState("");const [airbnbUrl,setAirbnbUrl]=useState("");const fileInput=useRef<HTMLInputElement>(null);const replaceInput=useRef<HTMLInputElement>(null);const [replaceIndex,setReplaceIndex]=useState<number|null>(null);
 const set=(key:string,value:unknown)=>setData(x=>({...x,[key]:value}));
 const save=async(status?:PropertyRecord["status"])=>{setSaving(true);const next={...data,status:status||data.status};if(initial){await fetch(`/api/admin/properties/${initial.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});setData(next);setSaving(false)}else{const r=await fetch("/api/admin/properties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const result=await r.json();await fetch(`/api/admin/properties/${result.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});location.href=`/admin/properties/${result.id}`}};
 const upload=async(files:FileList|File[],replaceAt?:number)=>{const list=Array.from(files);if(!list.length)return;if(list.length>50){setImageMessage("单次最多上传 50 张图片");return}setUploading(true);setImageMessage(`正在上传 ${list.length} 张图片…`);const form=new FormData();list.forEach(f=>form.append("files",f));const r=await fetch("/api/admin/uploads",{method:"POST",body:form});const result=await r.json();if(!r.ok){setImageMessage(result.error||"上传失败");setUploading(false);return}const urls=result.urls as string[];if(replaceAt!==undefined){const next=[...data.images];next[replaceAt]=urls[0];set("images",next)}else set("images",[...data.images,...urls]);setImageMessage(`已上传 ${urls.length} 张图片`);setUploading(false)};
 const importAirbnb=async()=>{if(!airbnbUrl)return;setUploading(true);setImageMessage("正在识别 Airbnb 房源图片…");const r=await fetch("/api/admin/import-airbnb",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:airbnbUrl})});const result=await r.json();if(r.ok){set("images",[...data.images,...result.urls]);setImageMessage(`已导入 ${result.urls.length} 张图片`);setAirbnbUrl("")}else setImageMessage(result.error||"导入失败");setUploading(false)};
 const move=(i:number,d:number)=>{const a=[...data.images],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];set("images",a)};
 const completeness=useMemo(()=>Math.round(([data.nameZh,data.nameEn,data.areaZh,data.images.length,data.descriptionZh,data.amenities.length,data.priceFrom].filter(Boolean).length/7)*100),[data]);
 return <div className="editor-page"><div className="editor-top"><div><Link href="/admin/properties">← 返回房源列表</Link><h1>{initial?data.nameZh||"编辑房源":"新增房源"}</h1><span>完成度 {completeness}% · {data.status==="published"?"已上线":data.status==="hidden"?"已隐藏":"草稿"}</span></div><div><button className="admin-secondary" onClick={()=>save()} disabled={saving}>{saving?"保存中…":"保存草稿"}</button><button className="admin-primary" onClick={()=>save("published")} disabled={saving}>发布房源</button></div></div><div className="editor-layout"><aside className="step-nav">{steps.map((x,i)=><button className={step===i?"active":i<step?"done":""} onClick={()=>setStep(i)} key={x}><i>{i<step?"✓":i+1}</i>{x}</button>)}</aside><section className="editor-form">{step===0&&<Block title="基础信息" desc="顾客最先看到的名称、地区和标签。"><Field label="中文名称"><input value={data.nameZh} onChange={e=>set("nameZh",e.target.value)}/></Field><Field label="英文名称"><input value={data.nameEn} onChange={e=>set("nameEn",e.target.value)}/></Field><div className="field-row"><Field label="城市"><select value={data.city} onChange={e=>set("city",e.target.value)}>{["吉隆坡","亚庇","仙本那"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="区域"><input value={data.areaZh} onChange={e=>set("areaZh",e.target.value)} placeholder="例如 KLCC"/></Field></div><Field label="标签（用逗号分隔）"><input value={data.tags.join(", ")} onChange={e=>set("tags",e.target.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean))} placeholder="家庭, 海景, 情侣"/></Field></Block>}
{step===1&&<Block title="图片管理" desc="支持拖拽或多选批量上传，单次最多 50 张；第一张图片默认作为房源封面。"><input ref={fileInput} className="hidden-file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple onChange={e=>e.target.files&&upload(e.target.files)}/><input ref={replaceInput} className="hidden-file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{if(e.target.files&&replaceIndex!==null)upload(e.target.files,replaceIndex);e.target.value=""}}/><div className={`upload-drop ${uploading?"busy":""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files)}}><b>⇧</b><h3>拖拽图片到这里批量上传</h3><p>支持 JPG、PNG、WebP、AVIF，单张不超过 15MB</p><button type="button" onClick={()=>fileInput.current?.click()} disabled={uploading}>选择多张图片</button></div><div className="airbnb-import"><div><b>从 Airbnb 自动导入</b><small>粘贴公开房源链接，自动识别并保存可访问图片</small></div><div><input value={airbnbUrl} onChange={e=>setAirbnbUrl(e.target.value)} placeholder="https://www.airbnb.com/rooms/…"/><button onClick={importAirbnb} disabled={uploading||!airbnbUrl}>识别图片</button></div></div>{imageMessage&&<p className="image-message">{imageMessage}</p>}<div className="media-toolbar"><b>房源图库</b><span>{data.images.length} 张 · 拖动卡片可排序，也可使用箭头</span></div><div className="image-list">{data.images.map((src,i)=><div draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("text/plain"));if(Number.isNaN(from)||from===i)return;const next=[...data.images];const [picked]=next.splice(from,1);next.splice(i,0,picked);set("images",next)}} key={`${src}-${i}`}><img src={src} alt=""/><span><b>{i===0?"★ 房源封面":`图片 ${i+1}`}</b><select value={data.imageCategories?.[src]||"未分类"} onChange={e=>set("imageCategories",{...(data.imageCategories||{}),[src]:e.target.value})}>{["未分类","外观","客厅","卧室","浴室","厨房","景观","设施","周边"].map(x=><option key={x}>{x}</option>)}</select></span><div><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button onClick={()=>move(i,1)} disabled={i===data.images.length-1}>↓</button>{i>0&&<button onClick={()=>set("images",[src,...data.images.filter((_,n)=>n!==i)])}>设封面</button>}<button onClick={()=>{setReplaceIndex(i);replaceInput.current?.click()}}>替换</button><button className="danger" onClick={()=>set("images",data.images.filter((_,n)=>n!==i))}>删除</button></div></div>)}</div></Block>}
{step===2&&<Block title="空间信息" desc="使用统一数字字段，让前台信息保持一致。"><div className="stat-inputs">{[["guests","入住人数"],["bedrooms","卧室"],["beds","床"],["bathrooms","浴室"]].map(([k,l])=><Field label={l} key={k}><input type="number" min="0" value={Number(data[k as keyof typeof data])} onChange={e=>set(k,Number(e.target.value))}/></Field>)}</div></Block>}
{step===3&&<Block title="房源介绍" desc="分别维护中文与英文介绍。"><Field label="关于这个房源"><textarea rows={7} value={data.descriptionZh} onChange={e=>set("descriptionZh",e.target.value)}/></Field><Field label="About this place"><textarea rows={7} value={data.descriptionEn} onChange={e=>set("descriptionEn",e.target.value)}/></Field></Block>}
{step===4&&<Block title="设施" desc="选择已有设施，前台会显示统一名称和图标。"><div className="amenity-checks">{amenityOptions.map(x=><label key={x}><input type="checkbox" checked={data.amenities.includes(x)} onChange={e=>set("amenities",e.target.checked?[...data.amenities,x]:data.amenities.filter(a=>a!==x))}/><span>{x}</span></label>)}</div></Block>}
{step===5&&<Repeater title="亮点" hint="例如：城市景观 / 晚上可以看到 KLCC 夜景" items={data.highlights} onChange={x=>set("highlights",x)} labels={["标题","描述"]}/>} 
{step===6&&<Repeater title="周边" hint="记录附近景点、类型和距离" items={data.nearby} onChange={x=>set("nearby",x)} labels={["地点名称","类型","距离"]}/>} 
{step===7&&<Block title="参考价格" desc="这里只展示起价，不形成订单或库存。"><Field label="Starting from"><div className="price-input"><span>RM</span><input type="number" value={data.priceFrom} onChange={e=>set("priceFrom",Number(e.target.value))}/><span>/ night</span></div></Field><Field label="价格备注"><input value={data.priceNote} onChange={e=>set("priceNote",e.target.value)}/></Field></Block>}
{step===8&&<Block title="发布检查" desc="保存草稿不会出现在前台；发布后顾客即可浏览。"><div className="publish-check"><b>{completeness}%</b><span>房源资料完成度</span><ul><li className={data.nameZh?"ok":""}>中英文名称</li><li className={data.images.length?"ok":""}>至少一张图片</li><li className={data.descriptionZh?"ok":""}>房源介绍</li><li className={data.priceFrom?"ok":""}>参考价格</li></ul><button className="admin-primary" onClick={()=>save("published")}>确认并发布</button></div></Block>}<div className="editor-next"><button disabled={step===0} onClick={()=>setStep(x=>x-1)}>上一步</button>{step<steps.length-1&&<button className="admin-primary" onClick={()=>setStep(x=>x+1)}>下一步</button>}</div></section><aside className="live-preview"><span>实时预览</span><div className="preview-card">{data.images[0]?<img src={data.images[0]} alt=""/>:<div className="empty-cover">添加封面图片</div>}<div><small>📍 {data.city}{data.areaZh?` · ${data.areaZh}`:""}</small><h2>{data.nameZh||"房源中文名称"}</h2><p>{data.guests} 位客人 · {data.bedrooms} 间卧室 · {data.beds} 张床 · {data.bathrooms} 间浴室</p><b>{data.priceFrom?`RM ${data.priceFrom} / night 起`:"参考价格待填写"}</b></div></div></aside></div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function Block({title,desc,children}:{title:string;desc:string;children:React.ReactNode}){return <><div className="block-head"><h2>{title}</h2><p>{desc}</p></div>{children}</>}
function Repeater({title,hint,items,onChange,labels}:{title:string;hint:string;items:Record<string,string>[];onChange:(x:Record<string,string>[])=>void;labels:string[]}){const keys=title==="亮点"?["title","description"]:["name","type","distance"];return <><div className="block-head"><h2>{title}</h2><p>{hint}</p></div><div className="repeater">{items.map((item,i)=><div key={i}>{keys.map((k,n)=><Field label={labels[n]} key={k}><input value={item[k]||""} onChange={e=>onChange(items.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}/></Field>)}<button onClick={()=>onChange(items.filter((_,j)=>j!==i))}>删除</button></div>)}<button className="add-row" onClick={()=>onChange([...items,Object.fromEntries(keys.map(k=>[k,""]))])}>＋ 添加{title}</button></div></>}
