"use client";
import Link from "next/link";import {useState} from "react";import type {PropertyRecord} from "../../../db/properties";
export function PropertyList({initialItems}:{initialItems:PropertyRecord[]}){
 const [items,setItems]=useState(initialItems);const [city,setCity]=useState("全部");const cities=["全部","吉隆坡","亚庇","仙本那"];
 const update=async(item:PropertyRecord,status:PropertyRecord["status"])=>{const next={...item,status};setItems(x=>x.map(y=>y.id===item.id?next:y));await fetch(`/api/admin/properties/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)})};
 const copy=async(item:PropertyRecord)=>{const response=await fetch("/api/admin/properties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nameZh:`${item.nameZh}（副本）`,nameEn:`${item.nameEn} Copy`,city:item.city,slug:`${item.slug}-copy`})});const {id}=await response.json();location.href=`/admin/properties/${id}`};
 const shown=items.filter(x=>city==="全部"||x.city===city);
 return <><div className="admin-head"><div><p>展示内容管理</p><h1>房源管理</h1><span>按地区管理住宿，编辑后即可同步前台展示。</span></div><Link className="admin-primary" href="/admin/properties/new">＋ 新增房源</Link></div><div className="city-tabs">{cities.map(x=><button className={city===x?"active":""} onClick={()=>setCity(x)} key={x}>{x}<small>{x==="全部"?items.length:items.filter(i=>i.city===x).length}</small></button>)}</div><div className="property-grid">{shown.map(item=><article className="property-admin-card" key={item.id}><div className="property-cover">{item.images[0]?<img src={item.images[0]} alt=""/>:<span>暂无图片</span>}<i className={item.status}>{item.status==="published"?"已上线":item.status==="hidden"?"已隐藏":"草稿"}</i></div><div className="property-card-body"><small>📍 {item.city} · {item.areaZh||"区域待填写"}</small><h2>{item.nameZh}</h2><p>{item.guests} 位客人　{item.bedrooms} 间卧室　{item.beds} 张床</p><b>RM {item.priceFrom || "—"} <small>/ night 起</small></b><div className="card-actions"><Link href={`/admin/properties/${item.id}`}>编辑</Link><Link target="_blank" href={`/rooms/${item.slug}`}>预览</Link><button onClick={()=>copy(item)}>复制</button><button onClick={()=>update(item,item.status==="published"?"hidden":"published")}>{item.status==="published"?"隐藏":"上线"}</button></div></div></article>)}</div></>
}
