import { env } from "cloudflare:workers";

export type ServiceCategory={id:number;slug:string;nameZh:string;nameEn:string;introZh:string;introEn:string;descriptionZh:string;descriptionEn:string;image:string;itemsZh:string[];itemsEn:string[];icon:string;sortOrder:number;visible:boolean;updatedAt:string};

const createSql=`CREATE TABLE IF NOT EXISTS service_categories (
 id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE, name_zh TEXT NOT NULL, name_en TEXT NOT NULL,
 intro_zh TEXT NOT NULL DEFAULT '', intro_en TEXT NOT NULL DEFAULT '', description_zh TEXT NOT NULL DEFAULT '', description_en TEXT NOT NULL DEFAULT '',
 image TEXT NOT NULL DEFAULT '', items_zh TEXT NOT NULL DEFAULT '[]', items_en TEXT NOT NULL DEFAULT '[]', icon TEXT NOT NULL DEFAULT '✦',
 sort_order INTEGER NOT NULL DEFAULT 0, visible INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;
const seeds=[
 ["private-car","私人包车与接送","Private Car & Transfers","舒适出行，自由安排路线","Comfortable travel with a flexible route","从机场抵达、城市游览到跨城市接送，我们根据人数和行程安排合适车辆与专业司机。","From airport arrivals and city travel to intercity transfers, we arrange a suitable vehicle and experienced driver.","https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=88",["亚庇私人包车","吉隆坡包车","机场接送","跨城市接送"],["Kota Kinabalu private car","Kuala Lumpur private car","Airport transfer","Intercity transfer"],"▱",1],
 ["island","海岛体验","Island Experiences","探索绝美海岛，畅享海洋乐趣","Discover beautiful islands and enjoy the sea","从亚庇到仙本那，协助安排适合家庭、朋友或情侣的海岛路线与接送。","From Kota Kinabalu to Semporna, we arrange island routes and transfers for families, friends and couples.","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=88",["亚庇跳岛","美人鱼岛","环滩岛","仙本那出海"],["Kota Kinabalu island hopping","Mantanani Island","Mengalum Island","Semporna island trips"],"≈",2],
 ["nature","生态体验","Nature Experiences","亲近自然，发现野生世界","Get closer to nature and wildlife","走进沙巴的红树林、热带雨林与高山环境，以轻松的节奏认识当地自然生态。","Explore Sabah's mangroves, rainforest and mountain landscapes at a relaxed pace.","https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1400&q=88",["红树林探索","萤火虫之旅","长鼻猴观察","神山自然体验"],["Mangrove exploration","Firefly tour","Proboscis monkey watching","Mount Kinabalu nature experience"],"♧",3],
 ["custom-trip","定制旅行","Custom Trips","专属规划，打造独一无二旅程","A personal itinerary designed around you","告诉我们同行人数、旅行天数和偏好，我们把住宿、交通与当地体验组合成顺畅的行程。","Tell us your group, travel days and preferences, and we will combine stays, transport and local experiences into one smooth trip.","https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=88",["多日行程规划","住宿＋包车组合","家庭旅行","蜜月旅行"],["Multi-day itinerary","Stay and private car package","Family travel","Honeymoon travel"],"⌖",4]
] as const;

export async function ensureServices(){await env.DB.prepare(createSql).run();const row=await env.DB.prepare("SELECT COUNT(*) total FROM service_categories").first<{total:number}>();if((row?.total||0)>0)return;for(const s of seeds)await env.DB.prepare(`INSERT INTO service_categories (slug,name_zh,name_en,intro_zh,intro_en,description_zh,description_en,image,items_zh,items_en,icon,sort_order,visible) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,1)`).bind(s[0],s[1],s[2],s[3],s[4],s[5],s[6],s[7],JSON.stringify(s[8]),JSON.stringify(s[9]),s[10],s[11]).run()}
const parse=(value:unknown)=>{try{return JSON.parse(String(value||"[]"))}catch{return []}};
export function mapService(row:Record<string,unknown>):ServiceCategory{return {id:Number(row.id),slug:String(row.slug),nameZh:String(row.name_zh),nameEn:String(row.name_en),introZh:String(row.intro_zh),introEn:String(row.intro_en),descriptionZh:String(row.description_zh),descriptionEn:String(row.description_en),image:String(row.image),itemsZh:parse(row.items_zh),itemsEn:parse(row.items_en),icon:String(row.icon),sortOrder:Number(row.sort_order),visible:Boolean(row.visible),updatedAt:String(row.updated_at)}}
export async function listServices(all=false){await ensureServices();const result=await env.DB.prepare(`SELECT * FROM service_categories ${all?"":"WHERE visible=1"} ORDER BY sort_order,id`).all();return result.results.map(x=>mapService(x as Record<string,unknown>))}
export async function getService(slug:string){await ensureServices();const row=await env.DB.prepare("SELECT * FROM service_categories WHERE slug=? AND visible=1").bind(slug).first();return row?mapService(row as Record<string,unknown>):null}
